//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Admin
    {
        public int Admin_id { get; set; }
        public string Admin_password { get; set; }
        public string Admin_token { get; set; }
        public Nullable<System.DateTime> Admin_lastLoginTime { get; set; }
    }
}
