//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Borrowing_record
    {
        public int BR_id { get; set; }
        public Nullable<int> B_id { get; set; }
        public Nullable<int> L_id { get; set; }
        public Nullable<System.DateTime> BR_datetime { get; set; }
        public Nullable<int> BR_renewalTimes { get; set; }
        public Nullable<System.DateTime> BR_returnedDate { get; set; }
        public System.DateTime BR_shouldReturnedDate { get; set; }
    }
}
