//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LibraryUser
    {
        public int L_id { get; set; }
        public string L_firstName { get; set; }
        public string L_lastName { get; set; }
        public Nullable<int> L_phoneNo { get; set; }
        public string L_email { get; set; }
        public string L_IDNo { get; set; }
        public Nullable<System.DateTime> L_birthday { get; set; }
        public string L_password { get; set; }
        public string L_accessRight { get; set; }
        public Nullable<System.DateTime> L_registerDatetime { get; set; }
        public bool L_isBan { get; set; }
    }
}
