//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rules
    {
        public int Rule_id { get; set; }
        public int Rule_borrowingLimit { get; set; }
        public int Rule_renewalLimit { get; set; }
        public int Rule_borrowingPeriod { get; set; }
        public int Rule_reservationLimit { get; set; }
        public double Rule_outDateFine { get; set; }
        public int Rule_limitRenewBookDay { get; set; }
        public string Rule_unlockPassword { get; set; }
    }
}
